/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;


import ticket.booking.Services.TrainServices;
import ticket.booking.Services.UserBookingServices;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        Scanner sc= new Scanner(System.in);
        UserBookingServices userBookingServices;
        TrainServices trainServices;

        int choice=0;
        //int internalChoice=0;

        while(choice!=7) {

            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");

            choice= sc.nextInt();
            try {
                userBookingServices= new UserBookingServices();
                trainServices= new TrainServices();
                switch (choice) {
                    case 1:
                        try {
                            userBookingServices.signUp();
                            break;
                        } catch (Exception e) {
                            System.out.println("Please try again");
                            break;
                        }
                    case 2:
                        try {
                            userBookingServices.loginUser();
                            break;
                        } catch (Exception e) {
                            System.out.println(e);
                            System.out.println("Something Went Wrong");
                            break;
                        }
                    case 3:
                        System.out.println("To Fetch the bookings, please login First.");
                        System.out.println("1. Should we take you to login page?");
                        System.out.println("2. Take me to the Home page.");
                        int case3Choice =sc.nextInt();
                        if(case3Choice ==1){
                        userBookingServices.loginUser();
                        break;}
                        else{
                            break;
                        }
                    case 4:
                        System.out.println("Please enter the Source");
                        String source= sc.next();
                        System.out.println("Please enter the destination");
                        String destination= sc.next();
                        trainServices.searchTrains(source,destination);

                        break;
                    case 5:
                        System.out.println("To book a Seat, please login First");
                        System.out.println("1. Should we take you to login page?");
                        System.out.println("2. Take me to the Home page.");
                        int case5Choice =sc.nextInt();
                        if(case5Choice ==1){
                            userBookingServices.loginUser();
                            break;}
                        else{
                            break;
                        }
                    case 6:
                        System.out.println("To cancel the bookings, please login First");
                        System.out.println("1. Should we take you to login page?");
                        System.out.println("2. Take me to the Home page.");
                        int case6Choice =sc.nextInt();
                        if(case6Choice ==1){
                            userBookingServices.loginUser();
                            break;}
                        else{
                            break;
                        }
                    case 7:
                        System.out.println("Thank you for checking out my small project :)");
                }
            } catch (Exception e) {
                System.out.println("Something Went Wrong");
            }
        }



    }
}
